"""empty message

Revision ID: 8aaeb165d8f3
Revises:
Create Date: 2025-04-21 11:21:26.270392

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8aaeb165d8f3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pokemon",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("height", sa.Float(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("base_experience", sa.Integer(), nullable=False),
        sa.Column("location_area_encounters", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pokemon")
    # ### end Alembic commands ###
